
public class Exercise8_2 {
//	java.lang.ArithmeticException : / by zero
//	at ExceptionEx18.method2(ExceptionEx18.java:12)
//	at ExceptionEx18.method1(ExceptionEx18.java:8)
//	at ExceptionEx18.main(ExceptionEx18.java:4)
	
//	a. 위의 내용으로 예외가 발생했을 당시 호출스택에 존재했던 메서드를 알 수 있다
//	b. 예외가 발생한 위치는 method2메서드이며 ExceptionEx18.java 12파일의 번째 줄이다
//	c. 발생한 예외는 ArithmeticException이며 0으로 나누어서 예외가 발생했다
//	d. method2메서드가 method1메서드를 호출하였고 그 위치는 ExceptionEx18.java파일의
//	8번째 줄이다. //  X -> method1메서드가 method2메서드를 호출 하였다.

}
