
public class ch8o4 {
//  void method() throws InvalidNumberException, NotANumberException {}
//  class NumberException extends RuntimeException {}
//  class InvalidNumberException extends NumberException {}
//  class NotANumberException extends NumberException {}
//  
//  a. try {method();} catch(Exception e) {}
//  b. try {method();} catch(NumberException e) {} catch(Exception e) {} --- Exception는 최상예외처리이며 모든 예외처리들은 Exception 아래에 상속되어있다. 그러므로 답은 b
//  c. try {method();} catch(Exception e) {} catch(NumberException e) {}
//  d. try {method();} catch(InvalidNumberException e) {
//  } catch(NotANumberException e) {}
//  e. try {method();} catch(NumberException e) {}
//  f. try {method();} catch(RuntimeException e) {}
  
}
